[package]
name = "rust-tcp-srv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kqueue = "1.0.8"
tokio = { version = "1", features = ["full"] }
bytes = "1"
